# Generated by Django 6.0.2 on 2026-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Netbanking'), ('MANUAL', 'Manual')], max_length=20),
        ),
    ]
